In [1]:
import os
import sys
import numpy as np
import pandas as pd
import pprint as pp
from pathlib import Path

sys.path.append(os.path.abspath(".."))

from utils.model_transformer.model import Model
from utils.model_ann.ann import build_index, search

device = "cpu"

# Load Dataset

In [2]:
# 현재 Jupyter Notebook 실행 경로 (e.g., `documents/recsys/3_modeling_lightgcn`)
current_dir = os.path.abspath(os.curdir)

# `../recsys` 경로
base_dir = "/".join(current_dir.split("/")[:-1])

# 데이터셋 경로
DOMAIN = "fashion"
dataset_dir = Path(base_dir).joinpath(f"data/dataset/{DOMAIN}/interactions")

df = pd.read_parquet(dataset_dir)
df.head()

,user_id,item_id,timestamp,action,age,gender,title,color,style,fit,material,season,sleeve,category
0,1,532,2025-09-21 03:01:00,click,46,F,간절기 한정 스웨이드 소재 그레이 조끼,그레이,미니멀,루즈핏,스웨이드,간절기,롱,조끼
1,1,2562,2025-09-21 03:02:00,click,46,F,미니멀 무드의 그레이 조끼,그레이,미니멀,슬림핏,레이온,간절기,롱슬리브,조끼
2,1,1886,2025-09-02 00:05:00,click,46,F,여름 한정 레이온 소재 베이지 재킷,베이지,레트로,레귤러핏,레이온,여름,민소매,재킷
3,1,5578,2025-09-23 20:44:00,click,46,F,그레이 컬러의 모던 스타일 아크릴 와이드팬츠,그레이,모던,크롭핏,아크릴,가을,숏슬리브,와이드팬츠
4,1,8329,2025-09-23 20:47:00,click,46,F,여름 한정 메쉬 소재 그레이 와이드팬츠,그레이,모던,오버핏,메쉬,여름,숏슬리브,와이드팬츠

# Load Model

In [3]:
model_dir = Path(base_dir).joinpath(f"data/model/{DOMAIN}")
model = Model(model_dir=model_dir)

/Users/hwangyungwan/miniforge3/envs/ds_p313/lib/python3.13/site-packages/torch/nn/modules/transformer.py:382: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(

# Prediction Test

In [4]:
# 예시 입력: user_id와 시퀀스
body = [
    {
        "user_id": 123,
        "inputs": [
            {
                "color": "화이트",
                "style": "캐주얼",
                "fit": "레귤러핏",
                "material": "코튼",
                "season": "가을",
                "sleeve": "롱",
                "category": "블라우스",
            },
            {
                "color": "그레이",
                "style": "포멀",
                "fit": "오버핏",
                "material": "퍼",
                "season": "가을",
                "sleeve": "롱",
                "category": "점퍼",
            },
        ],
    }
]

# Model.predict 호출 -> Transformer + Projection 결과 생성
prediction = model.predict(body)[0]
pp.pprint(prediction)
# 출력: {"outputs": feature별 예측 값, "seq_vector": [...], "item_vector": [...]}

{'item_vector': [0.01442360132932663,
                 0.020868388935923576,
                 -0.016097046434879303,
                 0.023031067103147507,
                 0.020023927092552185,
                 -0.023103876039385796,
                 -0.02238493785262108,
                 -0.03921019285917282,
                 0.026455450803041458,
                 0.0260159932076931,
                 -0.02560807764530182,
                 -0.007453098893165588,
                 0.16956312954425812,
                 0.025325514376163483,
                 -0.03943762928247452,
                 -0.03223380446434021,
                 0.0035494230687618256,
                 -0.024827294051647186,
                 0.07723300158977509,
                 0.009231358766555786,
                 0.04190237820148468,
                 -0.012957122176885605,
                 0.0489191971719265,
                 -0.024309653788805008,
                 0.02450486272573471,
                 -0.004919268190860748,
                 0.02127777226269245,
                 0.0431513674557209,
                 -0.04250169172883034,
                 0.047331444919109344,
                 0.030269723385572433,
                 -0.03318621218204498,
                 0.019152387976646423,
                 0.020083412528038025,
                 -0.0007379613816738129,
                 0.04168765991926193,
                 -0.03300531953573227,
                 -0.014169830828905106,
                 -0.0020260587334632874,
                 0.006067138165235519,
                 0.01353415846824646,
                 0.014816388487815857,
                 0.030871162191033363,
                 -0.04710696265101433,
                 0.018520072102546692,
                 -0.04986236244440079,
                 0.05371326208114624,
                 0.026784654706716537,
                 -0.03483102098107338,
                 -0.0034055300056934357,
                 0.02307502180337906,
                 0.010205671191215515,
                 0.015597793273627758,
                 -0.0017433837056159973,
                 -0.03550196811556816,
                 -0.03347089886665344,
                 0.03749081492424011,
                 0.009628735482692719,
                 -0.07176802307367325,
                 0.02567894756793976,
                 0.015776943415403366,
                 0.05329328775405884,
                 -0.02596401795744896,
                 0.00507730059325695,
                 0.05453900620341301,
                 -0.01913948729634285,
                 0.011538365855813026,
                 -0.020917896181344986,
                 -0.06215113028883934,
                 -0.0404062457382679,
                 0.0033533181995153427,
                 -0.03922794386744499,
                 0.06493063271045685,
                 -0.0058512091636657715,
                 -0.06792181730270386,
                 -0.018048642203211784,
                 -0.05574588477611542,
                 -0.004167657345533371,
                 -0.021830502897500992,
                 -0.03078969195485115,
                 0.04286089539527893,
                 0.01787220686674118,
                 0.008250828832387924,
                 0.015904784202575684,
                 -0.006250113248825073,
                 -0.0015581026673316956,
                 -0.021158842369914055,
                 0.026930876076221466,
                 0.03292321041226387,
                 0.05371278151869774,
                 0.008147962391376495,
                 -0.0418429933488369,
                 -0.029192667454481125,
                 0.042146578431129456,
                 0.003745250403881073,
                 0.020726278424263,
                 0.005214180797338486,
                 0.02708495408296585,
                 0.028563514351844788,
                 -0.03524777665734291,
                 0.009041991084814072,
                 -0.11598724126815796,
                 -0.016018982976675034,
                 -0.054359350353479385,
                 -0.07756076753139496,
                 -0.009133994579315186,
                 -0.014440175145864487,
                 -0.033023156225681305,
                 0.05881831794977188,
                 -0.010729335248470306,
                 -0.012781556695699692,
                 0.02984694391489029,
                 0.03729112073779106,
                 -0.04307688772678375,
                 0.031625714153051376,
                 -0.006502136588096619,
                 0.0312112495303154,
                 -0.02347557805478573,
                 0.012456968426704407,
                 -0.04754547402262688,
                 0.0039575546979904175,
                 0.023847749456763268,
                 -0.03675650805234909,
                 -0.04381967708468437,
                 0.031442832201719284,
                 -0.03330269083380699,
                 0.001428462564945221,
                 -0.020892195403575897,
                 0.05098944157361984,
                 -0.0494394525885582,
                 -0.010723277926445007,
                 -0.009223069995641708,
                 0.006710657849907875,
                 -0.00017718970775604248,
                 -0.00719161331653595,
                 0.04714614152908325,
                 0.043716948479413986,
                 0.03438278287649155,
                 -0.014878258109092712,
                 -0.01146114245057106,
                 0.0016210656613111496,
                 -0.06440466642379761,
                 0.007160443812608719,
                 0.01294957846403122,
                 0.04689028114080429,
                 -0.03979545086622238,
                 0.05099780857563019,
                 -0.006429893895983696,
                 -0.009858034551143646,
                 0.01236746646463871,
                 0.03166665881872177,
                 -0.08662959933280945,
                 -0.027542997151613235,
                 -0.022913632914423943,
                 0.019977502524852753,
                 0.011447818949818611,
                 -0.05521542206406593,
                 -0.02355140447616577,
                 0.008099167607724667,
                 0.04180087149143219,
                 0.046500466763973236,
                 0.026932459324598312,
                 0.035775404423475266,
                 -0.003746751695871353,
                 0.033346716314554214,
                 -0.00579732283949852,
                 0.011653285473585129,
                 0.012389864772558212,
                 0.005532760173082352,
                 -0.026611803099513054,
                 -0.013827571645379066,
                 -0.031801603734493256,
                 -0.04541178420186043,
                 0.021506836637854576,
                 -0.006217688322067261,
                 -0.011914648115634918,
                 -0.031996794044971466,
                 -0.026842549443244934,
                 -0.02907937578856945,
                 -0.028604160994291306,
                 -0.061999838799238205,
                 -0.045952603220939636,
                 -0.04737530276179314,
                 0.033256955444812775,
                 -0.007315635681152344,
                 -0.009618446230888367,
                 -0.010178204625844955,
                 -0.04217953234910965,
                 0.02031661570072174,
                 0.0022552236914634705,
                 0.0008200779557228088,
                 0.044521912932395935,
                 0.04521850496530533,
                 0.00992882065474987,
                 0.03256756812334061,
                 0.03432605043053627,
                 0.02561941370368004,
                 0.03401579707860947,
                 -0.013973314315080643,
                 -0.03118951991200447,
                 0.01246897503733635,
                 0.006840111687779427,
                 0.04576830565929413,
                 0.02919498085975647,
                 0.010750217363238335,
                 -0.050177570432424545,
                 -0.04079733416438103,
                 0.05566913262009621,
                 0.02066769450902939,
                 0.03655175864696503,
                 -0.021006014198064804,
                 0.033837877213954926,
                 -0.02348821610212326,
                 0.017025072127580643,
                 -0.03965989127755165,
                 -0.0317721888422966,
                 0.029812149703502655,
                 0.0006258627399802208,
                 -0.008642159402370453,
                 0.04879336804151535,
                 0.01523645967245102,
                 -0.05078241229057312,
                 0.05699335038661957,
                 0.02122856304049492,
                 -0.025502201169729233,
                 -0.011859998106956482,
                 0.014153897762298584,
                 -0.03841198980808258,
                 0.012314796447753906,
                 0.024815671145915985,
                 0.03401467949151993,
                 0.013994958251714706,
                 -0.03155655041337013,
                 0.0070267170667648315,
                 -0.020690277218818665,
                 -0.020836032927036285,
                 0.04961715638637543,
                 0.007997233420610428,
                 -0.012765191495418549,
                 -0.09174999594688416,
                 -0.03912944719195366,
                 0.025931546464562416,
                 0.015229053795337677,
                 -0.03680502995848656,
                 0.02203013189136982,
                 -0.034381505101919174,
                 -0.02616245672106743,
                 0.028941333293914795,
                 -0.04383503273129463,
                 0.029908310621976852,
                 -0.012693317607045174,
                 -0.02110322006046772,
                 0.017473965883255005,
                 -0.016669439151883125,
                 0.0007192585617303848,
                 -0.009702496230602264,
                 -0.018978184089064598,
                 0.01710008643567562,
                 -0.0027548708021640778,
                 0.014839760959148407,
                 -0.005786776542663574,
                 -0.05307859927415848,
                 -0.01694130152463913,
                 -0.03176729381084442,
                 0.023547612130641937,
                 0.007485892623662949,
                 0.06812076270580292,
                 -0.06066271662712097,
                 -0.05056876689195633,
                 -0.026127686724066734,
                 -0.020198095589876175,
                 -0.019951973110437393,
                 -0.05341092869639397,
                 0.02083577588200569,
                 0.015979504212737083,
                 -0.02737254649400711,
                 -0.04886695370078087,
                 0.011251237243413925,
                 -0.014861326664686203,
                 -0.021710295230150223,
                 -0.02540932595729828,
                 0.03097059205174446,
                 -0.036873526871204376,
                 -0.009374525398015976,
                 -0.03455927222967148,
                 0.01744769513607025,
                 -0.06912010908126831,
                 -0.0028956159949302673,
                 -0.061688512563705444,
                 0.030297547578811646,
                 0.027237575501203537,
                 0.05474620312452316,
                 -0.002208402380347252,
                 0.04805019125342369,
                 0.029769353568553925,
                 0.019196709617972374,
                 -0.01543174684047699,
                 0.0017372667789459229,
                 0.021915387362241745,
                 -0.015470370650291443,
                 -0.01932482048869133,
                 -0.013725798577070236,
                 0.012862425297498703,
                 -0.04944472014904022,
                 -0.030372314155101776,
                 0.011742860078811646,
                 0.12259936332702637,
                 0.042200397700071335,
                 -0.03654695674777031,
                 0.026795662939548492,
                 -0.028622960671782494,
                 -0.004604740999639034,
                 -0.04785311594605446,
                 0.0315060093998909,
                 0.034131668508052826,
                 -0.02438797801733017,
                 -0.008593231439590454,
                 0.05102577805519104,
                 0.003612130880355835,
                 0.03155555576086044,
                 0.021351005882024765,
                 0.03703410178422928,
                 -0.006666313856840134,
                 -0.01867940090596676,
                 0.03773089498281479,
                 -0.021037664264440536,
                 0.05321536958217621,
                 -0.019806846976280212,
                 0.09271637350320816,
                 0.012841358780860901,
                 -0.020366862416267395,
                 0.04281548783183098,
                 0.002692105248570442,
                 0.04024043679237366,
                 -0.03401043266057968,
                 0.018304087221622467,
                 -0.0563746839761734,
                 -0.04353407025337219,
                 0.10789042711257935,
                 0.012431319802999496,
                 -0.03580254688858986,
                 0.032426632940769196,
                 0.017146043479442596,
                 -0.01819753646850586,
                 0.04508870095014572,
                 -0.038807883858680725,
                 0.004714794456958771,
                 -0.06565111130475998,
                 -0.03474096581339836,
                 0.02141568437218666,
                 0.027160845696926117,
                 -0.058433350175619125,
                 0.015827838331460953,
                 -0.015117574483156204,
                 -0.0199909508228302,
                 0.01860230416059494,
                 0.02901587262749672,
                 -0.018642332404851913,
                 -0.024924900382757187,
                 -0.0076501816511154175,
                 -0.04446682706475258,
                 0.04689401760697365,
                 0.03621917963027954,
                 0.0011040829122066498,
                 -0.01230696216225624,
                 0.035649850964546204,
                 -0.007346427068114281,
                 0.004350114613771439,
                 0.04289226979017258,
                 -0.006903350353240967,
                 0.08964870870113373,
                 0.035889461636543274,
                 -0.02030663937330246,
                 -0.0011102557182312012,
                 0.04550276696681976,
                 -0.015196491032838821,
                 0.03507262095808983,
                 -0.05209992080926895,
                 -0.023774396628141403,
                 0.028185615316033363,
                 0.05965334177017212,
                 0.03375612944364548,
                 0.004087252542376518,
                 0.00399409607052803,
                 -0.0012705400586128235,
                 0.04058147966861725,
                 0.032805219292640686,
                 -0.04944157227873802,
                 0.016873005777597427,
                 -0.024487216025590897,
                 0.003620665520429611,
                 -0.007399231195449829,
                 -0.01942630484700203,
                 0.019638800993561745,
                 0.02823920175433159,
                 0.020059723407030106,
                 0.0056462362408638,
                 -0.0589548721909523,
                 0.02514973282814026,
                 -0.038796618580818176,
                 0.03917119279503822,
                 -0.005782760679721832,
                 -0.0206302460283041,
                 0.032088957726955414,
                 0.04860800504684448,
                 0.01305677741765976,
                 0.01642630249261856,
                 0.06276446580886841,
                 -0.013247412629425526,
                 -0.052145279943943024,
                 0.03875032812356949,
                 -0.032088201493024826,
                 0.041737448424100876,
                 -0.025166183710098267,
                 0.024942565709352493,
                 -0.040814489126205444,
                 -0.002137521281838417,
                 0.04404338449239731,
                 0.0003359168767929077,
                 0.003078719601035118,
                 -0.05215594172477722,
                 0.045969076454639435,
                 0.0243256613612175,
                 0.014214199036359787,
                 0.03474529832601547,
                 -0.08147943019866943,
                 -0.018675029277801514,
                 -0.010135370306670666,
                 0.0072507355362176895,
                 -0.035224851220846176,
                 -0.013591986149549484,
                 0.02003786526620388,
                 0.007500525563955307,
                 -0.002440154552459717,
                 0.0024308189749717712,
                 -0.040287554264068604,
                 0.040192704647779465,
                 0.016044601798057556,
                 -0.010212313383817673,
                 0.014071755111217499,
                 0.0041902512311935425,
                 -0.01624501496553421,
                 0.004491075873374939,
                 -0.02514023706316948,
                 -0.02834610641002655,
                 -0.00768415117636323,
                 -0.036660779267549515,
                 -0.023742254823446274,
                 -0.037685856223106384,
                 0.008932799100875854,
                 0.03845394402742386,
                 0.01048249751329422,
                 0.026501987129449844,
                 -0.0012637972831726074,
                 0.014881931245326996,
                 -0.018772954121232033,
                 0.026839569211006165,
                 -0.028096787631511688,
                 -0.0009157694876194,
                 -0.10209891200065613,
                 0.03275853395462036,
                 0.031204376369714737,
                 -0.0020643044263124466,
                 0.0006307009607553482,
                 0.009194061160087585,
                 -0.06860833615064621,
                 0.019710097461938858,
                 -0.04338882490992546,
                 0.029803233221173286,
                 -0.03213698789477348,
                 -0.043123625218868256,
                 -0.003293316811323166,
                 0.013730797916650772,
                 0.01746409758925438,
                 0.03453425318002701,
                 0.032111477106809616,
                 -0.008313655853271484,
                 0.0220809169113636,
                 0.039170630276203156,
                 -0.042205993086099625,
                 0.010416336357593536,
                 0.003326382488012314,
                 -0.025744128972291946,
                 0.0376189723610878,
                 0.008757680654525757,
                 0.03464654088020325,
                 -0.09921103715896606,
                 0.06537409871816635,
                 0.018041422590613365,
                 -0.012494146823883057,
                 -0.00015413202345371246,
                 0.030256593599915504,
                 0.038521599024534225,
                 -0.030875634402036667,
                 0.026757927611470222,
                 0.030288830399513245,
                 -0.019815528765320778,
                 -0.07094060629606247,
                 0.021032564342021942,
                 0.01634049415588379,
                 -0.018222570419311523,
                 0.009188510477542877,
                 -0.06034884601831436,
                 0.011151369661092758,
                 -0.037851668894290924,
                 0.0020501986145973206,
                 -0.04011701047420502,
                 0.030900901183485985,
                 0.03645899146795273,
                 -0.023525040596723557,
                 0.08173926919698715,

# Recommendation

In [5]:
# 아이템 메타데이터 로드
item_metadata_path = Path(base_dir).joinpath(
    f"data/dataset/{DOMAIN}/item_metadata.parquet"
)
df_item = pd.read_parquet(item_metadata_path)

In [6]:
# 텍스트 기반 아이템 벡터 로드
text_vectors_path = Path(base_dir).joinpath(
    f"data/dataset/{DOMAIN}/text_vectors.parquet"
)
df_text_vectors = pd.read_parquet(text_vectors_path)

# text_vectors: (num_items, dim) numpy float32 배열
text_vectors = np.array(df_text_vectors["text_vector"].tolist())
item_vectors = np.array(text_vectors).astype(np.float32)

# {item index: item_id} 매핑
# (`df_text_vectors.index는` row index이므로 range(0..N-1)로 반환함)
item_id_maps = dict(zip(df_text_vectors["item_id"].index, df_text_vectors["item_id"]))

In [7]:
# 아이템 벡터 ANN 인덱스 생성
item_index = build_index(item_vectors)

In [8]:
# projection 모델에서 뽑은 item vector
query_vector = np.array(prediction["item_vector"])

# 아이템 벡터 인덱스에 질의한 결과 획득
result = search(query_vector, item_index, top_k=30)

# 추천 아이템 ID (원본 ID가 아닌 별도의 인덱스)
item_indies = list(result.keys())

# 추천 아이템 ID 재매핑
recommendation = {}
for i in item_indies:
    # 원본 ID로 매핑
    item_id = item_id_maps[i]
    recommendation[item_id] = result[i]

recommendation

{4134: 0.9762977361679077,
 7631: 0.97479647397995,
 6654: 0.9747697710990906,
 3014: 0.9744164943695068,
 6401: 0.9743509292602539,
 6134: 0.9743276834487915,
 8793: 0.9742951393127441,
 8273: 0.9742439985275269,
 1291: 0.974220335483551,
 4913: 0.9742075204849243,
 1064: 0.973919689655304,
 8477: 0.9737474322319031,
 4526: 0.9735881090164185,
 5157: 0.9735623598098755,
 2663: 0.9735464453697205,
 80: 0.973492443561554,
 3936: 0.9734611511230469,
 9025: 0.9734115600585938,
 6144: 0.9733580350875854,
 2758: 0.9733424186706543,
 808: 0.9733152985572815,
 7743: 0.9733009338378906,
 2974: 0.9732850790023804,
 8947: 0.9732571840286255,
 9443: 0.9732523560523987,
 5737: 0.9732134938240051,
 5944: 0.9731569290161133,
 3463: 0.9730831384658813,
 9428: 0.9730818271636963,
 4219: 0.9730344414710999}

In [9]:
# 추천 아이템 후보군 상세 보기
df_recommendation = df_item[
    df_item["item_id"].isin(list(recommendation.keys()))
].reset_index(drop=True)

df_recommendation

,item_id,title,color,style,fit,material,season,sleeve,category
0,80,봄 감성 루즈핏 메쉬 원피스,민트,모던,루즈핏,메쉬,봄,롱슬리브,원피스
1,808,겨울 감성 루즈핏 퍼 후드티,레드,캐주얼,루즈핏,퍼,겨울,롱,후드티
2,1064,여름 감성 크롭핏 모달 슬랙스,아이보리,빈티지,크롭핏,모달,여름,숏슬리브,슬랙스
3,1291,겨울 감성 루즈핏 메쉬 스커트,민트,캐주얼,루즈핏,메쉬,겨울,숏,스커트
4,2663,가을 감성 루즈핏 아크릴 니트,스카이블루,스포티,루즈핏,아크릴,가을,7부,니트
5,2758,가을 감성 루즈핏 아크릴 재킷,민트,포멀,루즈핏,아크릴,가을,숏,재킷
6,2974,겨울 감성 크롭핏 모달 재킷,오렌지,미니멀,크롭핏,모달,겨울,롱슬리브,재킷
7,3014,봄 감성 크롭핏 폴리 후드티,브라운,포멀,크롭핏,폴리,봄,롱슬리브,후드티
8,3463,봄 감성 레귤러핏 모달 스커트,스카이블루,러블리,레귤러핏,모달,봄,롱슬리브,스커트
9,3936,봄 감성 레귤러핏 스웨이드 원피스,스카이블루,댄디,레귤러핏,스웨이드,봄,숏,원피스
10,4134,봄 감성 크롭핏 모달 슬랙스,카키,시크,크롭핏,모달,봄,민소매,슬랙스
11,4219,봄 감성 오버핏 스웨이드 재킷,핑크,러블리,오버핏,스웨이드,봄,롱,재킷
12,4526,가을 감성 루즈핏 메쉬 원피스,민트,레트로,루즈핏,메쉬,가을,7부,원피스
13,4913,가을 감성 루즈핏 메쉬 스커트,와인,레트로,루즈핏,메쉬,가을,7부,스커트
14,5157,가을 감성 루즈핏 스웨이드 점퍼,그레이,레트로,루즈핏,스웨이드,가을,롱,점퍼
15,5737,가을 감성 루즈핏 아크릴 스커트,카키,빈티지,루즈핏,아크릴,가을,롱,스커트
16,5944,겨울 감성 오버핏 데님 재킷,레드,스트리트,오버핏,데님,겨울,7부,재킷
17,6134,겨울 감성 레귤러핏 모달 슬랙스,블랙,댄디,레귤러핏,모달,겨울,롱,슬랙스
18,6144,봄 감성 크롭핏 데님 재킷,오렌지,미니멀,크롭핏,데님,봄,롱,재킷
19,6401,가을 감성 레귤러핏 모달 슬랙스,오렌지,스트리트,레귤러핏,모달,가을,민소매,슬랙스
20,6654,봄 감성 크롭핏 폴리 스커트,블랙,러블리,크롭핏,폴리,봄,숏슬리브,스커트
21,7631,가을 감성 루즈핏 울 후드티,블랙,레트로,루즈핏,울,가을,롱슬리브,후드티
22,7743,여름 감성 루즈핏 울 후드티,화이트,댄디,루즈핏,울,여름,숏,후드티
23,8273,가을 감성 루즈핏 코튼 후드티,와인,스트리트,루즈핏,코튼,가을,민소매,후드티
24,8477,봄 감성 크롭핏 폴리 니트,아이보리,미니멀,크롭핏,폴리,봄,롱슬리브,니트
25,8793,봄 감성 크롭핏 메쉬 슬랙스,네이비,스트리트,크롭핏,메쉬,봄,숏,슬랙스
26,8947,겨울 감성 크롭핏 모달 니트,와인,포멀,크롭핏,모달,겨울,7부,니트
27,9025,가을 감성 루즈핏 모달 코트,네이비,시크,루즈핏,모달,가을,민소매,코트
28,9428,봄 감성 루즈핏 스웨이드 레깅스,민트,댄디,루즈핏,스웨이드,봄,민소매,레깅스
29,9443,가을 감성 루즈핏 가죽 후드티,카키,스포티,루즈핏,가죽,가을,숏,후드티