In [14]:
import os
import sys
import numpy as np
import pandas as pd
import pprint as pp
from pathlib import Path

sys.path.append(os.path.abspath(".."))

from utils.model_transformer.model import Model
from utils.model_ann.ann import build_index, search

device = "cpu"

# Load Dataset

In [15]:
# 현재 Jupyter Notebook 실행 경로 (e.g., `documents/recsys/3_modeling_lightgcn`)
current_dir = os.path.abspath(os.curdir)

# `../recsys` 경로
base_dir = "/".join(current_dir.split("/")[:-1])

# 데이터셋 경로
DOMAIN = "fashion"
dataset_dir = Path(base_dir).joinpath(f"data/dataset/{DOMAIN}/interactions")

df = pd.read_parquet(dataset_dir)
df.head()

,user_id,item_id,timestamp,action,age,gender,title,color,style,fit,material,season,sleeve,category
0,1,2194,2025-09-21 03:01:00,click,46,F,블랙 컬러의 스포티 스타일 레이온 청바지,블랙,스포티,레귤러핏,레이온,봄,롱,청바지
1,1,4723,2025-09-21 03:02:00,click,46,F,크롭핏 실루엣의 메쉬 청바지,블랙,스포티,크롭핏,메쉬,가을,롱,청바지
2,1,2689,2025-09-02 00:05:00,click,46,F,빈티지 무드의 레드 티셔츠,레드,빈티지,슬림핏,플리스,여름,롱,티셔츠
3,1,7981,2025-09-02 00:09:00,click,46,F,"겨울 시즌, 빈티지 무드의 레드 플리스 숏슬리브 크롭핏 티셔츠",레드,빈티지,크롭핏,플리스,겨울,숏슬리브,티셔츠
4,1,1770,2025-09-02 00:11:00,wishlist,46,F,필수템! 빈티지 무드의 간절기용 티셔츠,레드,빈티지,오버핏,린넨,간절기,롱슬리브,티셔츠

# Load Model

In [16]:
model_dir = Path(base_dir).joinpath(f"data/model/{DOMAIN}")
model = Model(model_dir=model_dir)

/Users/hwangyungwan/miniforge3/envs/ds_p313/lib/python3.13/site-packages/torch/nn/modules/transformer.py:382: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(

# Prediction Test

In [17]:
# 예시 입력: user_id와 시퀀스
body = [
    {
        "user_id": 123,
        "inputs": [
            {
                "color": "화이트",
                "style": "캐주얼",
                "fit": "레귤러핏",
                "material": "코튼",
                "season": "가을",
                "sleeve": "롱",
                "category": "블라우스",
            },
            {
                "color": "그레이",
                "style": "포멀",
                "fit": "오버핏",
                "material": "퍼",
                "season": "가을",
                "sleeve": "롱",
                "category": "점퍼",
            },
        ],
    }
]

# Model.predict 호출 -> Transformer + Projection 결과 생성
prediction = model.predict(body)[0]
pp.pprint(prediction)
# 출력: {"outputs": feature별 예측 값, "seq_vector": [...], "item_vector": [...]}

{'item_vector': [0.009297627955675125,
                 0.02260192111134529,
                 -0.017447881400585175,
                 0.0198733601719141,
                 0.018183201551437378,
                 -0.023382477462291718,
                 -0.01977570913732052,
                 -0.0398319810628891,
                 0.02563830465078354,
                 0.02977462112903595,
                 -0.02858254685997963,
                 -0.004372846335172653,
                 0.17078927159309387,
                 0.02507835254073143,
                 -0.04340161383152008,
                 -0.029127087444067,
                 0.004410089924931526,
                 -0.02628120221197605,
                 0.07400678843259811,
                 0.011680535972118378,
                 0.03986535966396332,
                 -0.01330642495304346,
                 0.050895776599645615,
                 -0.021583905443549156,
                 0.021659059450030327,
                 -0.005516815930604935,
                 0.027084670960903168,
                 0.04131316766142845,
                 -0.04208790138363838,
                 0.05035492032766342,
                 0.031003568321466446,
                 -0.03546120226383209,
                 0.021956637501716614,
                 0.020503640174865723,
                 -0.0005135312676429749,
                 0.04584966599941254,
                 -0.031934112310409546,
                 -0.01839124970138073,
                 -0.0028925687074661255,
                 0.005474906414747238,
                 0.014252390712499619,
                 0.016889112070202827,
                 0.03272562474012375,
                 -0.04779217764735222,
                 0.011838078498840332,
                 -0.05513472855091095,
                 0.05537734925746918,
                 0.02702609822154045,
                 -0.0383763425052166,
                 -0.007840756326913834,
                 0.022367356345057487,
                 0.004799434915184975,
                 0.01378769800066948,
                 0.00019515305757522583,
                 -0.040830519050359726,
                 -0.03400170058012009,
                 0.036709826439619064,
                 0.007936323061585426,
                 -0.0692242756485939,
                 0.026196464896202087,
                 0.017216719686985016,
                 0.056436896324157715,
                 -0.022724714130163193,
                 0.0022519081830978394,
                 0.055796533823013306,
                 -0.01768556982278824,
                 0.014764197170734406,
                 -0.018485205247998238,
                 -0.05832888185977936,
                 -0.04231072962284088,
                 0.0024631842970848083,
                 -0.03719831258058548,
                 0.06059812009334564,
                 -0.006668031215667725,
                 -0.06341905891895294,
                 -0.014909384772181511,
                 -0.059305377304553986,
                 -0.006211049854755402,
                 -0.01583775132894516,
                 -0.030991695821285248,
                 0.03787943720817566,
                 0.01603209599852562,
                 0.009340658783912659,
                 0.016604162752628326,
                 -0.0035878680646419525,
                 -0.005304095335304737,
                 -0.01798022910952568,
                 0.029084427282214165,
                 0.027724258601665497,
                 0.0584164559841156,
                 0.010636422783136368,
                 -0.043353140354156494,
                 -0.03184453770518303,
                 0.0410001277923584,
                 0.0008291527628898621,
                 0.019643642008304596,
                 0.005280066281557083,
                 0.024853523820638657,
                 0.030444249510765076,
                 -0.03242616355419159,
                 0.006512217223644257,
                 -0.11251603811979294,
                 -0.015691354870796204,
                 -0.054941825568675995,
                 -0.0784686878323555,
                 -0.015323803760111332,
                 -0.015990804880857468,
                 -0.03436820209026337,
                 0.05933091789484024,
                 -0.015120012685656548,
                 -0.012596232816576958,
                 0.029925405979156494,
                 0.04036594554781914,
                 -0.03899586200714111,
                 0.032901935279369354,
                 -0.005102604627609253,
                 0.028124578297138214,
                 -0.017970889806747437,
                 0.008359100669622421,
                 -0.0509670190513134,
                 0.002414427697658539,
                 0.019923921674489975,
                 -0.038778893649578094,
                 -0.041761621832847595,
                 0.034592241048812866,
                 -0.03279479965567589,
                 0.0017494149506092072,
                 -0.016632094979286194,
                 0.05306755751371384,
                 -0.04506920278072357,
                 -0.007154747843742371,
                 -0.0075356848537921906,
                 0.005241364240646362,
                 0.002347085624933243,
                 -0.010086841881275177,
                 0.045579083263874054,
                 0.042825616896152496,
                 0.034213561564683914,
                 -0.00831747055053711,
                 -0.004190821200609207,
                 0.011125989258289337,
                 -0.06873674690723419,
                 0.008037421852350235,
                 0.009057220071554184,
                 0.05007393658161163,
                 -0.04352015256881714,
                 0.05050981044769287,
                 -0.0062548816204071045,
                 -0.013592302799224854,
                 0.016046635806560516,
                 0.03023824468255043,
                 -0.08546379953622818,
                 -0.02964489534497261,
                 -0.02685573138296604,
                 0.02098865807056427,
                 0.01121469959616661,
                 -0.050785765051841736,
                 -0.026849154382944107,
                 0.0007189959287643433,
                 0.042932845652103424,
                 0.04983352869749069,
                 0.029293648898601532,
                 0.03244044631719589,
                 -0.0030799340456724167,
                 0.03560987487435341,
                 -0.002074688673019409,
                 0.009151164442300797,
                 0.01461060345172882,
                 0.01142650842666626,
                 -0.024274121969938278,
                 -0.01811317726969719,
                 -0.034504927694797516,
                 -0.047025762498378754,
                 0.022041015326976776,
                 -0.004659939557313919,
                 -0.01120712049305439,
                 -0.035153187811374664,
                 -0.02611195296049118,
                 -0.0313020795583725,
                 -0.02867645025253296,
                 -0.06204694136977196,
                 -0.041895367205142975,
                 -0.05041182041168213,
                 0.03256014734506607,
                 -0.006070412695407867,
                 -0.00874166190624237,
                 -0.0073991939425468445,
                 -0.044183146208524704,
                 0.021903742104768753,
                 0.0011083697900176048,
                 -0.0068137310445308685,
                 0.04090398550033569,
                 0.044451501220464706,
                 0.01590031012892723,
                 0.032943665981292725,
                 0.03174315392971039,
                 0.02211987040936947,
                 0.0364096462726593,
                 -0.013022080063819885,
                 -0.03436299040913582,
                 0.015309246256947517,
                 0.007733747363090515,
                 0.05021233111619949,
                 0.02726360782980919,
                 0.010292932391166687,
                 -0.0496501699090004,
                 -0.03593403846025467,
                 0.054852478206157684,
                 0.02005220577120781,
                 0.04091760516166687,
                 -0.024308692663908005,
                 0.032351844012737274,
                 -0.02410753071308136,
                 0.01767789199948311,
                 -0.0443897619843483,
                 -0.029681183397769928,
                 0.03456035256385803,
                 -0.002343500033020973,
                 -0.0039022713899612427,
                 0.05148846656084061,
                 0.017244063317775726,
                 -0.04593217000365257,
                 0.05993732437491417,
                 0.01996733993291855,
                 -0.025089113041758537,
                 -0.012515336275100708,
                 0.013779886066913605,
                 -0.03694777935743332,
                 0.009886734187602997,
                 0.01931198127567768,
                 0.03245394676923752,
                 0.011342888697981834,
                 -0.03226785361766815,
                 -0.000849161297082901,
                 -0.023343976587057114,
                 -0.02109348773956299,
                 0.05071183294057846,
                 0.0072614578530192375,
                 -0.016570784151554108,
                 -0.09315105527639389,
                 -0.04345042631030083,
                 0.026383081451058388,
                 0.01124277338385582,
                 -0.03467424213886261,
                 0.021036483347415924,
                 -0.03486672788858414,
                 -0.022241204977035522,
                 0.028703205287456512,
                 -0.04430343583226204,
                 0.03658955916762352,
                 -0.011259062215685844,
                 -0.023358341306447983,
                 0.019910089671611786,
                 -0.019055277109146118,
                 -0.0012993905693292618,
                 -0.0032380223274230957,
                 -0.02036038041114807,
                 0.018568210303783417,
                 -0.006695069372653961,
                 0.01015592459589243,
                 -0.0095168836414814,
                 -0.0492171011865139,
                 -0.015620505437254906,
                 -0.035075847059488297,
                 0.025156885385513306,
                 0.0030919164419174194,
                 0.06911678612232208,
                 -0.06131325662136078,
                 -0.05415354669094086,
                 -0.02783847600221634,
                 -0.0219319686293602,
                 -0.019573520869016647,
                 -0.05442304164171219,
                 0.016869664192199707,
                 0.01988077349960804,
                 -0.029013291001319885,
                 -0.05137331038713455,
                 0.013699237257242203,
                 -0.011874016374349594,
                 -0.019850067794322968,
                 -0.025779560208320618,
                 0.02915780246257782,
                 -0.03878068923950195,
                 -0.006969638168811798,
                 -0.03463706746697426,
                 0.015398021787405014,
                 -0.06849215924739838,
                 0.0012994743883609772,
                 -0.06251376122236252,
                 0.030123643577098846,
                 0.024421727284789085,
                 0.050144970417022705,
                 -0.002513572573661804,
                 0.04959144443273544,
                 0.030225319787859917,
                 0.022640595212578773,
                 -0.015607185661792755,
                 0.002077728509902954,
                 0.021823816001415253,
                 -0.011522289365530014,
                 -0.021910805255174637,
                 -0.022316060960292816,
                 0.014533141627907753,
                 -0.05292891710996628,
                 -0.029227210208773613,
                 0.010929159820079803,
                 0.12373378127813339,
                 0.047542866319417953,
                 -0.042239848524332047,
                 0.028174659237265587,
                 -0.02966836839914322,
                 -0.008765415288507938,
                 -0.044510744512081146,
                 0.03105752542614937,
                 0.03687038645148277,
                 -0.029798362404108047,
                 -0.007437072694301605,
                 0.0519074946641922,
                 0.0013260245323181152,
                 0.03574301674962044,
                 0.023898087441921234,
                 0.03657073527574539,
                 -0.006048664450645447,
                 -0.021601784974336624,
                 0.03260939568281174,
                 -0.020205169916152954,
                 0.05452745407819748,
                 -0.01998244971036911,
                 0.09177011996507645,
                 0.009174872189760208,
                 -0.022084660828113556,
                 0.04065138101577759,
                 0.007956795394420624,
                 0.03977774828672409,
                 -0.03555205091834068,
                 0.019910505041480064,
                 -0.058677755296230316,
                 -0.04057532548904419,
                 0.10853537917137146,
                 0.017926275730133057,
                 -0.035251930356025696,
                 0.03438912332057953,
                 0.02105414867401123,
                 -0.014967601746320724,
                 0.042640410363674164,
                 -0.03567058593034744,
                 0.004255019128322601,
                 -0.06446129083633423,
                 -0.029308069497346878,
                 0.022187836468219757,
                 0.02609013020992279,
                 -0.058189135044813156,
                 0.01526867225766182,
                 -0.010378647595643997,
                 -0.016611292958259583,
                 0.018031146377325058,
                 0.03637445718050003,
                 -0.0191273782402277,
                 -0.026843372732400894,
                 -0.009086847305297852,
                 -0.04416573792695999,
                 0.04366402328014374,
                 0.034845009446144104,
                 0.0036908090114593506,
                 -0.01036582700908184,
                 0.03202075883746147,
                 -0.009465456008911133,
                 -0.0008352752774953842,
                 0.04337511956691742,
                 -0.010232612490653992,
                 0.09441760182380676,
                 0.03433037921786308,
                 -0.02512960135936737,
                 -0.002651222050189972,
                 0.04633229225873947,
                 -0.01608274132013321,
                 0.035552963614463806,
                 -0.053591012954711914,
                 -0.018032528460025787,
                 0.026357606053352356,
                 0.0668950006365776,
                 0.030497029423713684,
                 0.006782642565667629,
                 0.0010947808623313904,
                 0.0025468729436397552,
                 0.03980324789881706,
                 0.02534983865916729,
                 -0.04051720350980759,
                 0.018981710076332092,
                 -0.022489968687295914,
                 0.005559276789426804,
                 -0.005967721343040466,
                 -0.01679835096001625,
                 0.02018381468951702,
                 0.0373382531106472,
                 0.014935143291950226,
                 0.007292546331882477,
                 -0.055615611374378204,
                 0.026914671063423157,
                 -0.04334738105535507,
                 0.041631925851106644,
                 -0.003728225827217102,
                 -0.017834346741437912,
                 0.031145786866545677,
                 0.049742262810468674,
                 0.011552020907402039,
                 0.01555369421839714,
                 0.06343173235654831,
                 -0.018096301704645157,
                 -0.05148229002952576,
                 0.03871238976716995,
                 -0.031117230653762817,
                 0.044532667845487595,
                 -0.020907187834382057,
                 0.023565609008073807,
                 -0.03587685525417328,
                 -0.004951898008584976,
                 0.0462617389857769,
                 0.0019529908895492554,
                 -0.00018439628183841705,
                 -0.05735357105731964,
                 0.04519275203347206,
                 0.02651377022266388,
                 0.02100105583667755,
                 0.0326266810297966,
                 -0.08521955460309982,
                 -0.01844446361064911,
                 -0.007723622024059296,
                 0.0026264041662216187,
                 -0.03025362640619278,
                 -0.01845666393637657,
                 0.020895488560199738,
                 0.013561081141233444,
                 0.0005155541002750397,
                 0.004729118198156357,
                 -0.04474857449531555,
                 0.037374742329120636,
                 0.017174094915390015,
                 -0.007894132286310196,
                 0.010447680950164795,
                 0.003419701009988785,
                 -0.013680361211299896,
                 0.003917204216122627,
                 -0.018439091742038727,
                 -0.026503968983888626,
                 -0.006490003317594528,
                 -0.038451921194791794,
                 -0.021753907203674316,
                 -0.04428926110267639,
                 0.009005023166537285,
                 0.029721535742282867,
                 0.007664376869797707,
                 0.027494311332702637,
                 0.001795303076505661,
                 0.016791369765996933,
                 -0.018017277121543884,
                 0.027550071477890015,
                 -0.025697002187371254,
                 -0.00205210130661726,
                 -0.1001870334148407,
                 0.03451967611908913,
                 0.03214070945978165,
                 0.0007040277123451233,
                 0.001857370138168335,
                 0.006149120628833771,
                 -0.06478101015090942,
                 0.021654658019542694,
                 -0.04341701790690422,
                 0.02795211598277092,
                 -0.03768269345164299,
                 -0.04626132920384407,
                 -0.005720619112253189,
                 0.014135632663965225,
                 0.009073758497834206,
                 0.033310964703559875,
                 0.03570529818534851,
                 -0.009520642459392548,
                 0.022914862260222435,
                 0.03590463101863861,
                 -0.04455670341849327,
                 0.009787902235984802,
                 0.002065509557723999,
                 -0.027326975017786026,
                 0.03394922986626625,
                 0.009959366172552109,
                 0.030408576130867004,
                 -0.09475936740636826,
                 0.0639047622680664,
                 0.016980033367872238,
                 -0.008406552486121655,
                 0.0006109625101089478,
                 0.03207683935761452,
                 0.03981216251850128,
                 -0.030971616506576538,
                 0.03368372470140457,
                 0.028684724122285843,
                 -0.012868988327682018,
                 -0.07095853984355927,
                 0.020205114036798477,
                 0.016894441097974777,
                 -0.012149723246693611,
                 0.005378648638725281,
                 -0.06252189725637436,
                 0.013380814343690872,
                 -0.03472407907247543,
                 0.006069831550121307,
                 -0.04127076640725136,
                 0.03737456351518631,
                 0.03559708595275879,
                 -0.021352488547563553,
                 0.0779089629650116,

# Recommendation

In [18]:
# 상품 메타데이터 로드
item_metadata_path = Path(base_dir).joinpath(
    f"data/dataset/{DOMAIN}/item_metadata.parquet"
)
df_item = pd.read_parquet(item_metadata_path)

In [19]:
# 텍스트 기반 상품 벡터 로드
text_vectors_path = Path(base_dir).joinpath(
    f"data/dataset/{DOMAIN}/text_vectors.parquet"
)
df_text_vectors = pd.read_parquet(text_vectors_path)

# text_vectors: (num_items, dim) numpy float32 배열
text_vectors = np.array(df_text_vectors["text_vector"].tolist())
item_vectors = np.array(text_vectors).astype(np.float32)

# {item index: item_id} 매핑
# (`df_text_vectors.index는` row index이므로 range(0..N-1)로 반환함)
item_id_maps = dict(zip(df_text_vectors["item_id"].index, df_text_vectors["item_id"]))

In [20]:
# 상품 벡터 ANN 인덱스 생성
item_index = build_index(item_vectors)

In [21]:
# projection 모델에서 뽑은 item vector
query_vector = np.array(prediction["item_vector"])

# 상품 벡터 인덱스에 질의한 결과 획득
result = search(query_vector, item_index, top_k=30)

# 추천 상품 ID (원본 ID가 아닌 별도의 인덱스)
item_indies = list(result.keys())

# 추천 상품 ID 재매핑
recommendation = {}
for i in item_indies:
    # 원본 ID로 매핑
    item_id = item_id_maps[i]
    recommendation[item_id] = result[i]

recommendation

{3792: 0.9729532599449158,
 8654: 0.9728444814682007,
 5137: 0.9727115035057068,
 633: 0.9725723266601562,
 818: 0.9724801182746887,
 3857: 0.9723662734031677,
 7951: 0.9723052382469177,
 3205: 0.9723004102706909,
 5549: 0.9722353219985962,
 5126: 0.9722210168838501,
 9186: 0.9718894362449646,
 5308: 0.971874475479126,
 1180: 0.9717846512794495,
 9323: 0.9716914892196655,
 3718: 0.9715550541877747,
 4151: 0.971531093120575,
 7830: 0.9714600443840027,
 2847: 0.9713377356529236,
 8970: 0.9713141918182373,
 6060: 0.9712381362915039,
 5021: 0.9712255001068115,
 7816: 0.9712125658988953,
 5396: 0.971118688583374,
 8415: 0.9710777401924133,
 7909: 0.9709604978561401,
 5723: 0.9708784222602844,
 9393: 0.9708486795425415,
 7467: 0.9707375764846802,
 631: 0.9706350564956665,
 2044: 0.9706182479858398}

In [22]:
# 추천 상품 후보군 상세 보기
df_recommendation = df_item[
    df_item["item_id"].isin(list(recommendation.keys()))
].reset_index(drop=True)

df_recommendation

,item_id,title,color,style,fit,material,season,sleeve,category
0,631,가을 감성 루즈핏 코튼 카디건,그레이,댄디,루즈핏,코튼,가을,숏슬리브,카디건
1,633,가을 감성 레귤러핏 코튼 후드티,올리브,댄디,레귤러핏,코튼,가을,롱슬리브,후드티
2,818,가을 감성 오버핏 모달 재킷,그레이,러블리,오버핏,모달,가을,숏슬리브,재킷
3,1180,가을 루즈핏 카키 린넨 숏 후드티,카키,시크,루즈핏,린넨,가을,숏,후드티
4,2044,여름 크롭핏 카키 울 롱 후드티,카키,미니멀,크롭핏,울,여름,롱,후드티
5,2847,가을 감성 레귤러핏 데님 슬랙스,아이보리,빈티지,레귤러핏,데님,가을,숏,슬랙스
6,3205,여름 감성 크롭핏 모달 재킷,스카이블루,빈티지,크롭핏,모달,여름,7부,재킷
7,3718,겨울 감성 크롭핏 데님 후드티,블랙,시크,크롭핏,데님,겨울,롱,후드티
8,3792,가을 감성 루즈핏 메쉬 스커트,오렌지,시크,루즈핏,메쉬,가을,7부,스커트
9,3857,겨울 감성 레귤러핏 폴리 후드티,베이지,시크,레귤러핏,폴리,겨울,숏슬리브,후드티
10,4151,가을 감성 레귤러핏 스웨이드 슬랙스,아이보리,댄디,레귤러핏,스웨이드,가을,숏슬리브,슬랙스
11,5021,봄 감성 오버핏 코튼 후드티,민트,시크,오버핏,코튼,봄,롱,후드티
12,5126,가을 감성 루즈핏 퍼 슬랙스,라벤더,포멀,루즈핏,퍼,가을,7부,슬랙스
13,5137,가을 감성 크롭핏 폴리 니트,브라운,댄디,크롭핏,폴리,가을,숏,니트
14,5308,가을 감성 루즈핏 폴리 재킷,화이트,미니멀,루즈핏,폴리,가을,롱슬리브,재킷
15,5396,가을 감성 크롭핏 모달 와이드팬츠,와인,미니멀,크롭핏,모달,가을,숏,와이드팬츠
16,5549,가을 감성 슬림핏 모달 재킷,스카이블루,댄디,슬림핏,모달,가을,숏,재킷
17,5723,가을 감성 오버핏 메쉬 슬랙스,와인,스포티,오버핏,메쉬,가을,숏슬리브,슬랙스
18,6060,겨울 감성 루즈핏 린넨 후드티,베이지,포멀,루즈핏,린넨,겨울,롱슬리브,후드티
19,7467,여름 감성 크롭핏 모달 원피스,와인,러블리,크롭핏,모달,여름,숏슬리브,원피스
20,7816,가을 감성 크롭핏 린넨 슬랙스,민트,시크,크롭핏,린넨,가을,민소매,슬랙스
21,7830,여름 감성 레귤러핏 모달 슬랙스,카키,스트리트,레귤러핏,모달,여름,숏,슬랙스
22,7909,가을 감성 레귤러핏 데님 스커트,민트,댄디,레귤러핏,데님,가을,롱,스커트
23,7951,가을 감성 루즈핏 퍼 스커트,블랙,포멀,루즈핏,퍼,가을,7부,스커트
24,8415,가을 감성 크롭핏 스웨이드 코트,와인,레트로,크롭핏,스웨이드,가을,롱,코트
25,8654,가을 감성 레귤러핏 스웨이드 원피스,핑크,미니멀,레귤러핏,스웨이드,가을,롱슬리브,원피스
26,8970,봄 감성 크롭핏 스웨이드 재킷,라벤더,댄디,크롭핏,스웨이드,봄,롱슬리브,재킷
27,9186,가을 감성 슬림핏 퍼 후드티,스카이블루,러블리,슬림핏,퍼,가을,숏슬리브,후드티
28,9323,가을 감성 크롭핏 데님 원피스,레드,레트로,크롭핏,데님,가을,롱,원피스
29,9393,여름 루즈핏 화이트 코튼 숏 후드티,화이트,빈티지,루즈핏,코튼,여름,숏,후드티