In [1]:
import os
import sys
import numpy as np
import pandas as pd
from pathlib import Path

sys.path.append(os.path.abspath(".."))

from utils.model_ann.ann import build_index, search

# Load Dataset

In [2]:
# 현재 Jupyter Notebook 실행 경로 (e.g., `documents/recsys/3_modeling_lightgcn`)
current_dir = os.path.abspath(os.curdir)

# `../recsys` 경로
base_dir = "/".join(current_dir.split("/")[:-1])

# 데이터셋 경로
DOMAIN = "fashion"
dataset_dir = Path(base_dir).joinpath(f"data/dataset/{DOMAIN}/interactions")

df = pd.read_parquet(dataset_dir)
df.head()

,user_id,item_id,timestamp,action,age,gender,title,color,style,fit,material,season,sleeve,category
0,1,1842,2025-09-21 03:01:00,click,46,F,"봄 시즌, 시크 무드의 와인 코튼 숏슬리브 루즈핏 니트",와인,시크,루즈핏,코튼,봄,숏슬리브,니트
1,1,6061,2025-09-21 03:02:00,click,46,F,"겨울 시즌, 시크 무드의 와인 가죽 7부 슬림핏 니트",와인,시크,슬림핏,가죽,겨울,7부,니트
2,1,5578,2025-09-21 03:03:00,click,46,F,오버핏 실루엣의 퍼 니트,와인,시크,오버핏,퍼,가을,롱,니트
3,1,6550,2025-09-07 07:32:00,click,46,F,간절기에 어울리는 와인 원피스,와인,미니멀,레귤러핏,레이온,간절기,롱슬리브,원피스
4,1,1476,2025-09-07 07:35:00,wishlist,46,F,세미오버핏 실루엣의 플리스 원피스,와인,미니멀,세미오버핏,플리스,가을,7부,원피스

# Load Embedding Vectors

In [3]:
# 벡터 저장 경로 설정 (base_dir 아래에 도메인별 LightGCN 결과물이 저장된 폴더 지정)
vector_path = Path(base_dir).joinpath(f"data/model/{DOMAIN}/lightgcn")

# User / Item 벡터 파일 로드
df_user_vectors = pd.read_parquet(vector_path.joinpath("user_vector.parquet"))
df_item_vectors = pd.read_parquet(vector_path.joinpath("item_vector.parquet"))

# ID 매핑 딕셔너리 생성 (ANN 검색 후 결과를 실제 ID로 변환할 때 필요)
user_id_maps = dict(zip(df_user_vectors["idx"], df_user_vectors["user_id"]))
item_id_maps = dict(zip(df_item_vectors["idx"], df_item_vectors["item_id"]))

# 벡터(Numpy 배열) 변환
user_vectors = np.array(df_user_vectors["vector_normalized"].tolist())
item_vectors = np.array(df_item_vectors["vector_normalized"].tolist())

# 데이터 타입 변환 (ANN 라이브러리(HNSWlib, FAISS 등)에서 효율적으로 사용하기 위해 float32로 맞춤)
user_vectors = np.array(user_vectors).astype(np.float32)
item_vectors = np.array(item_vectors).astype(np.float32)

# Vector Similarity Search

## User Similarity

In [4]:
# 유저 벡터 ANN 인덱스 생성
user_index = build_index(user_vectors)

# 질의할 유저 선택
user_idx = 0
query_vector = user_vectors[user_idx]  # 해당 유저의 임베딩 벡터

# ANN 검색 실행 (`query_vector`와 가장 가까운 Top-5 유저 탐색)
result = search(query_vector, user_index, top_k=5)
print(result)  # 예: {1: 0.9, 2: 0.8, ...}

{0: 1.0000001192092896, 3214: 0.6490262150764465, 1952: 0.5046886205673218, 5187: 0.5021470189094543, 4667: 0.47915810346603394}

In [5]:
# 질의 유저의 히스토리 조회 (어떤 아이템들에 관심이 있었는지)
user_id = user_id_maps[user_idx]

print(f"User ID: {user_id}")
print("-----------------------------------")
for t in sorted(df[df["user_id"] == user_id]["title"].unique()):
    print(t)

User ID: 1
-----------------------------------
가을 감성 세미오버핏 가죽 원피스
가을 감성 오버핏 플리스 청바지
가을에 어울리는 화이트 코트
간절기 시즌, 미니멀 무드의 브라운 메쉬 민소매 슬림핏 원피스
간절기에 어울리는 와인 원피스
겨울 시즌, 댄디 무드의 화이트 폴리 롱슬리브 루즈핏 코트
겨울 시즌, 시크 무드의 와인 가죽 7부 슬림핏 니트
루즈핏 실루엣의 데님 원피스
미니멀 무드의 브라운 원피스
봄 시즌, 시크 무드의 와인 코튼 숏슬리브 루즈핏 니트
빈티지 무드의 카키 청바지
세미오버핏 실루엣의 플리스 원피스
여름 감성 크롭핏 린넨 원피스
오버핏 실루엣의 퍼 니트
필수템! 댄디 무드의 여름용 코트

In [6]:
# 유사 유저의 히스토리 조회 (어떤 아이템들에 관심이 있었는지)
similar_indies = list(result.keys())[1:]  # 첫 번째는 자기 자신과의 유사도이므로 제외
similar_user_ids = [user_id_maps[i] for i in similar_indies]

for uid in similar_user_ids:
    print(f"\nUser ID: {uid}")
    print("-----------------------------------")
    for t in sorted(df[df["user_id"] == uid]["title"]):
        print(t)

User ID: 3215
-----------------------------------
가을 감성 루즈핏 아크릴 슬랙스
가을 감성 세미오버핏 가죽 원피스
가을 감성 오버핏 아크릴 니트
가을 크롭핏 라벤더 가죽 롱 후드티
간절기 시즌, 미니멀 무드의 브라운 메쉬 민소매 슬림핏 원피스
간절기 한정 퍼 소재 그레이 원피스
간절기에 어울리는 그레이 원피스
그레이 컬러의 포멀 스타일 가죽 원피스
레드 컬러의 러블리 스타일 데님 슬랙스
미니멀 무드의 브라운 원피스
봄 루즈핏 레드 가죽 7부 슬랙스
봄 세미오버핏 브라운 모달 7부 니트
브라운 컬러의 스포티 스타일 나일론 니트
세미오버핏 실루엣의 린넨 니트
여름 감성 슬림핏 데님 원피스
여름 감성 크롭핏 린넨 원피스
여름 시즌, 미니멀 무드의 라벤더 폴리 롱 크롭핏 후드티
여름 한정 울 소재 레드 슬랙스
트렌디한 미니멀룩, 크롭핏 후드티 in 가을

User ID: 1953
-----------------------------------
간절기에 어울리는 화이트 후드티
겨울 감성 슬림핏 스웨이드 후드티
겨울 시즌, 빈티지 무드의 핑크 폴리 롱 레귤러핏 베스트
겨울 한정 메쉬 소재 레드 청바지
겨울 한정 플리스 소재 브라운 코트
댄디 무드의 레드 청바지
봄에 어울리는 핑크 베스트
여름 시즌, 시크 무드의 화이트 레이온 7부 레귤러핏 후드티
여름 시즌, 캐주얼 무드의 브라운 가죽 숏 세미오버핏 코트
여름 한정 가죽 소재 화이트 후드티
여름에 어울리는 그레이 조끼
오버핏 실루엣의 스웨이드 베스트
캐주얼 무드의 브라운 코트
트렌디한 러블리룩, 슬림핏 조끼 in 여름
트렌디한 캐주얼룩, 슬림핏 코트 in 간절기
필수템! 빈티지 무드의 여름용 베스트

User ID: 5188
-----------------------------------
가을 감성 세미오버핏 가죽 원피스
가을 루즈핏 핑크 플리스 숏 맨투맨
가을 크롭핏 라벤더 가죽 롱 후드티
간절기 슬림핏 그레이 스웨이드 숏 베스트
간절기 시즌, 미니멀 무드의 브라운 메쉬 민소매 슬림핏 원피스
그레이 컬러의 시크 스타일 린넨 베스트
미니멀 무드의 브라운 원피스
시크 무드의 그레이 베스트
여름 감성 크롭핏 린넨 원피스
여름 세미오버핏 핑크 플리스 롱 맨투맨
여름 시즌, 미니멀 무드의 라벤더 폴리 롱 크롭핏 후드티
여름 시즌, 시크 무드의 그레이 퍼 7부 레귤러핏 베스트
트렌디한 미니멀룩, 크롭핏 후드티 in 가을
트렌디한 포멀룩, 오버핏 맨투맨 in 봄
포멀 무드의 핑크 맨투맨
필수템! 시크 무드의 가을용 오버롤
필수템! 시크 무드의 봄용 오버롤
필수템! 포멀 무드의 여름용 맨투맨

User ID: 4668
-----------------------------------
가을 감성 세미오버핏 가죽 원피스
가을 루즈핏 블랙 코튼 숏 티셔츠
가을 시즌, 포멀 무드의 베이지 아크릴 롱 루즈핏 카디건
간절기 슬림핏 그레이 스웨이드 숏 베스트
간절기 시즌, 댄디 무드의 블랙 퍼 7부 크롭핏 티셔츠
간절기 시즌, 미니멀 무드의 브라운 메쉬 민소매 슬림핏 원피스
간절기 한정 레이온 소재 블랙 티셔츠
겨울 한정 폴리 소재 브라운 셔츠
미니멀 무드의 브라운 원피스
베이지 컬러의 포멀 스타일 모달 카디건
시크 무드의 그레이 베스트
여름 감성 크롭핏 린넨 원피스
여름 시즌, 시크 무드의 그레이 퍼 7부 레귤러핏 베스트
여름 한정 코튼 소재 베이지 카디건
포멀 무드의 브라운 셔츠
필수템! 포멀 무드의 간절기용 셔츠

## Item Similarity

In [7]:
# 아이템 벡터 ANN 인덱스 생성
item_index = build_index(item_vectors)

# 질의할 아이템 선택
item_idx = 0
query_vector = item_vectors[item_idx]  # 해당 아이템의 임베딩 벡터

# ANN 검색 실행 (`query_vector`와 가장 가까운 Top-5 아이템 탐색)
result = search(query_vector, item_index, top_k=5)
print(result)  # 예: {1: 0.9, 2: 0.8, ...}

{0: 1.0000001192092896, 2048: 0.991865873336792, 3418: 0.98921799659729, 9233: 0.9868526458740234, 1103: 0.44563573598861694}

In [8]:
# 아이템 유사성을 확인하기 위한 메타 데이터 로드
item_metadata_path = Path(base_dir).joinpath(
    f"data/dataset/{DOMAIN}/item_metadata.parquet"
)
df_item = pd.read_parquet(item_metadata_path)

In [9]:
# 질의 아이템 제목 조회
item_id = item_id_maps[item_idx]

print(f"Item ID: {item_id}")
print(df_item[df_item["item_id"] == item_id]["title"].item())

Item ID: 1
필수템! 댄디 무드의 겨울용 베스트

In [10]:
# 유사 아이템 제목 조회
similar_indies = list(result.keys())[1:]  # 첫 번째는 자기 자신과의 유사도이므로 제외
similar_item_ids = [item_id_maps[i] for i in similar_indies]

for item_id in similar_item_ids:
    print(f"\nItem ID: {item_id}")
    print("-----------------------------------")
    for t in sorted(df_item[df_item["item_id"] == item_id]["title"]):
        print(t)

Item ID: 2050
-----------------------------------
가을에 어울리는 그레이 베스트

Item ID: 3421
-----------------------------------
필수템! 댄디 무드의 가을용 베스트

Item ID: 9240
-----------------------------------
겨울 한정 울 소재 그레이 베스트

Item ID: 1105
-----------------------------------
화이트 컬러의 빈티지 스타일 퍼 카디건

# Recommendation
- User to Item 추천

In [11]:
# 질의 유저 선택
user_idx = 0
query_vector = user_vectors[user_idx]

# 아이템 벡터 인덱스에 질의한 결과 획득
result = search(query_vector, item_index, top_k=10)

# 추천 아이템 ID (원본 ID가 아닌 별도의 인덱스)
item_indies = list(result.keys())

# 추천 아이템 ID 재매핑
recommendation = {}
for i in item_indies:
    # 원본 ID로 매핑
    item_id = item_id_maps[i]
    recommendation[item_id] = result[i]

recommendation

{2655: 0.688797652721405,
 6550: 0.6820058822631836,
 1476: 0.6760274767875671,
 6374: 0.6653109192848206,
 7637: 0.6637354493141174,
 2718: 0.6627192497253418,
 4390: 0.6557523608207703,
 5951: 0.6343636512756348,
 3995: 0.6294198632240295,
 5578: 0.6092991232872009}

In [12]:
# 추천 아이템 상세 보기
df_recommendation = df_item[
    df_item["item_id"].isin(list(recommendation.keys()))
].reset_index(drop=True)

# 추천 아이템 점수(유사도) 추가
df_recommendation["score"] = df_recommendation["item_id"].map(recommendation)

# 점수별 내림차순 정렬
df_recommendation = df_recommendation.sort_values(
    "score", ascending=False, ignore_index=True
)

In [13]:
# 해당 유저의 히스토리 조회
df[df["user_id"] == user_id_maps[user_idx]].reset_index(drop=True)

,user_id,item_id,timestamp,action,age,gender,title,color,style,fit,material,season,sleeve,category
0,1,1842,2025-09-21 03:01:00,click,46,F,"봄 시즌, 시크 무드의 와인 코튼 숏슬리브 루즈핏 니트",와인,시크,루즈핏,코튼,봄,숏슬리브,니트
1,1,6061,2025-09-21 03:02:00,click,46,F,"겨울 시즌, 시크 무드의 와인 가죽 7부 슬림핏 니트",와인,시크,슬림핏,가죽,겨울,7부,니트
2,1,5578,2025-09-21 03:03:00,click,46,F,오버핏 실루엣의 퍼 니트,와인,시크,오버핏,퍼,가을,롱,니트
3,1,6550,2025-09-07 07:32:00,click,46,F,간절기에 어울리는 와인 원피스,와인,미니멀,레귤러핏,레이온,간절기,롱슬리브,원피스
4,1,1476,2025-09-07 07:35:00,wishlist,46,F,세미오버핏 실루엣의 플리스 원피스,와인,미니멀,세미오버핏,플리스,가을,7부,원피스
5,1,2655,2025-09-07 07:34:00,click,46,F,루즈핏 실루엣의 데님 원피스,와인,미니멀,루즈핏,데님,겨울,숏,원피스
6,1,7637,2025-09-06 22:27:00,purchase,46,F,빈티지 무드의 카키 청바지,카키,빈티지,오버핏,스웨이드,여름,롱,청바지
7,1,3995,2025-09-06 22:30:00,click,46,F,가을 감성 오버핏 플리스 청바지,카키,빈티지,오버핏,플리스,가을,숏,청바지
8,1,9840,2025-09-13 03:22:00,click,46,F,필수템! 댄디 무드의 여름용 코트,화이트,댄디,루즈핏,데님,여름,민소매,코트
9,1,7519,2025-09-13 03:26:00,click,46,F,"겨울 시즌, 댄디 무드의 화이트 폴리 롱슬리브 루즈핏 코트",화이트,댄디,루즈핏,폴리,겨울,롱슬리브,코트
10,1,1833,2025-09-13 03:28:00,wishlist,46,F,가을에 어울리는 화이트 코트,화이트,댄디,슬림핏,가죽,가을,7부,코트
11,1,2718,2025-09-20 11:36:00,wishlist,46,F,가을 감성 세미오버핏 가죽 원피스,브라운,미니멀,세미오버핏,가죽,가을,숏슬리브,원피스
12,1,6374,2025-09-20 11:37:00,click,46,F,여름 감성 크롭핏 린넨 원피스,브라운,미니멀,크롭핏,린넨,여름,7부,원피스
13,1,5951,2025-09-20 11:44:00,click,46,F,미니멀 무드의 브라운 원피스,브라운,미니멀,레귤러핏,아크릴,간절기,민소매,원피스
14,1,4390,2025-09-20 11:45:00,click,46,F,"간절기 시즌, 미니멀 무드의 브라운 메쉬 민소매 슬림핏 원피스",브라운,미니멀,슬림핏,메쉬,간절기,민소매,원피스

In [14]:
# 추천 아이템 최종 후보군 조회
df_recommendation

,item_id,title,color,style,fit,material,season,sleeve,category,score
0,2655,루즈핏 실루엣의 데님 원피스,와인,미니멀,루즈핏,데님,겨울,숏,원피스,0.688798
1,6550,간절기에 어울리는 와인 원피스,와인,미니멀,레귤러핏,레이온,간절기,롱슬리브,원피스,0.682006
2,1476,세미오버핏 실루엣의 플리스 원피스,와인,미니멀,세미오버핏,플리스,가을,7부,원피스,0.676027
3,6374,여름 감성 크롭핏 린넨 원피스,브라운,미니멀,크롭핏,린넨,여름,7부,원피스,0.665311
4,7637,빈티지 무드의 카키 청바지,카키,빈티지,오버핏,스웨이드,여름,롱,청바지,0.663735
5,2718,가을 감성 세미오버핏 가죽 원피스,브라운,미니멀,세미오버핏,가죽,가을,숏슬리브,원피스,0.662719
6,4390,"간절기 시즌, 미니멀 무드의 브라운 메쉬 민소매 슬림핏 원피스",브라운,미니멀,슬림핏,메쉬,간절기,민소매,원피스,0.655752
7,5951,미니멀 무드의 브라운 원피스,브라운,미니멀,레귤러핏,아크릴,간절기,민소매,원피스,0.634364
8,3995,가을 감성 오버핏 플리스 청바지,카키,빈티지,오버핏,플리스,가을,숏,청바지,0.629420
9,5578,오버핏 실루엣의 퍼 니트,와인,시크,오버핏,퍼,가을,롱,니트,0.609299