In [1]:
import os
import sys
import numpy as np
import pandas as pd
from pathlib import Path

sys.path.append(os.path.abspath(".."))

from utils.model_ann.ann import build_index, search

# Load Dataset

In [2]:
# 현재 Jupyter Notebook 실행 경로 (e.g., `documents/recsys/3_modeling_lightgcn`)
current_dir = os.path.abspath(os.curdir)

# `../recsys` 경로
base_dir = "/".join(current_dir.split("/")[:-1])

# 데이터셋 경로
DOMAIN = "fashion"
dataset_dir = Path(base_dir).joinpath(f"data/dataset/{DOMAIN}/interactions")

df = pd.read_parquet(dataset_dir)
df.head()

,user_id,item_id,timestamp,action,age,gender,title,color,style,fit,material,season,sleeve,category
0,1,2194,2025-09-21 03:01:00,click,46,F,블랙 컬러의 스포티 스타일 레이온 청바지,블랙,스포티,레귤러핏,레이온,봄,롱,청바지
1,1,4723,2025-09-21 03:02:00,click,46,F,크롭핏 실루엣의 메쉬 청바지,블랙,스포티,크롭핏,메쉬,가을,롱,청바지
2,1,2689,2025-09-02 00:05:00,click,46,F,빈티지 무드의 레드 티셔츠,레드,빈티지,슬림핏,플리스,여름,롱,티셔츠
3,1,7981,2025-09-02 00:09:00,click,46,F,"겨울 시즌, 빈티지 무드의 레드 플리스 숏슬리브 크롭핏 티셔츠",레드,빈티지,크롭핏,플리스,겨울,숏슬리브,티셔츠
4,1,1770,2025-09-02 00:11:00,wishlist,46,F,필수템! 빈티지 무드의 간절기용 티셔츠,레드,빈티지,오버핏,린넨,간절기,롱슬리브,티셔츠

# Load Embedding Vectors

In [3]:
# 벡터 저장 경로 설정 (base_dir 아래에 도메인별 LightGCN 결과물이 저장된 폴더 지정)
vector_path = Path(base_dir).joinpath(f"data/model/{DOMAIN}/lightgcn")

# User / Item 벡터 파일 로드
df_user_vectors = pd.read_parquet(vector_path.joinpath("user_vector.parquet"))
df_item_vectors = pd.read_parquet(vector_path.joinpath("item_vector.parquet"))

# ID 매핑 딕셔너리 생성 (ANN 검색 후 결과를 실제 ID로 변환할 때 필요)
user_id_maps = dict(zip(df_user_vectors["idx"], df_user_vectors["user_id"]))
item_id_maps = dict(zip(df_item_vectors["idx"], df_item_vectors["item_id"]))

# 벡터(Numpy 배열) 변환
user_vectors = np.array(df_user_vectors["vector_normalized"].tolist())
item_vectors = np.array(df_item_vectors["vector_normalized"].tolist())

# 데이터 타입 변환 (ANN 라이브러리(HNSWlib, FAISS 등)에서 효율적으로 사용하기 위해 float32로 맞춤)
user_vectors = np.array(user_vectors).astype(np.float32)
item_vectors = np.array(item_vectors).astype(np.float32)

# Vector Similarity Search

## User Similarity

In [4]:
# 유저 벡터 ANN 인덱스 생성
user_index = build_index(user_vectors)

# 질의할 유저 선택
user_idx = 0
query_vector = user_vectors[user_idx]  # 해당 유저의 임베딩 벡터

# ANN 검색 실행 (`query_vector`와 가장 가까운 Top-5 유저 탐색)
result = search(query_vector, user_index, top_k=5)
print(result)  # 예: {1: 0.9, 2: 0.8, ...}

{0: 1.0000001192092896, 4356: 0.7162047624588013, 2187: 0.562408447265625, 5413: 0.5351565480232239, 7423: 0.5069608688354492}

In [5]:
# 질의 유저의 히스토리 조회 (어떤 상품들에 관심이 있었는지)
user_id = user_id_maps[user_idx]

print(f"User ID: {user_id}")
print("-----------------------------------")
for t in sorted(df[df["user_id"] == user_id]["title"].unique()):
    print(t)

User ID: 1
-----------------------------------
가을 시즌, 댄디 무드의 올리브 폴리 롱 슬림핏 스커트
간절기 슬림핏 레드 모달 민소매 티셔츠
간절기 시즌, 빈티지 무드의 그레이 울 숏 크롭핏 카디건
간절기 오버핏 올리브 린넨 숏 스커트
간절기 한정 메쉬 소재 그레이 카디건
간절기에 어울리는 그레이 카디건
겨울 시즌, 빈티지 무드의 레드 플리스 숏슬리브 크롭핏 티셔츠
베이지 컬러의 시크 스타일 울 니트
블랙 컬러의 스포티 스타일 레이온 청바지
빈티지 무드의 레드 티셔츠
슬림핏 실루엣의 린넨 스커트
시크 무드의 베이지 니트
크롭핏 실루엣의 메쉬 청바지
트렌디한 댄디룩, 슬림핏 스커트 in 가을
트렌디한 빈티지룩, 루즈핏 카디건 in 겨울
트렌디한 시크룩, 오버핏 니트 in 봄
필수템! 빈티지 무드의 간절기용 티셔츠

In [6]:
# 유사 유저의 히스토리 조회 (어떤 상품들에 관심이 있었는지)
similar_indies = list(result.keys())[1:]  # 첫 번째는 자기 자신과의 유사도이므로 제외
similar_user_ids = [user_id_maps[i] for i in similar_indies]

for uid in similar_user_ids:
    print(f"\nUser ID: {uid}")
    print("-----------------------------------")
    for t in sorted(df[df["user_id"] == uid]["title"]):
        print(t)

User ID: 4357
-----------------------------------
가을 세미오버핏 아이보리 플리스 7부 원피스
가을 시즌, 댄디 무드의 올리브 폴리 롱 슬림핏 스커트
가을 시즌, 러블리 무드의 와인 레이온 7부 오버핏 카디건
간절기 오버핏 올리브 린넨 숏 스커트
베이지 컬러의 시크 스타일 울 니트
시크 무드의 베이지 니트
여름 세미오버핏 화이트 나일론 롱슬리브 베스트
여름 한정 나일론 소재 와인 카디건
트렌디한 댄디룩, 슬림핏 스커트 in 가을
트렌디한 시크룩, 오버핏 니트 in 봄
필수템! 레트로 무드의 간절기용 원피스
필수템! 레트로 무드의 여름용 원피스

User ID: 2188
-----------------------------------
가을 감성 루즈핏 울 베스트
가을 감성 크롭핏 퍼 레깅스
가을 시즌, 시크 무드의 라벤더 가죽 롱 오버핏 베스트
가을 한정 레이온 소재 올리브 블라우스
겨울 루즈핏 올리브 모달 숏슬리브 블라우스
겨울 크롭핏 레드 레이온 롱슬리브 티셔츠
겨울 크롭핏 올리브 데님 민소매 블라우스
라벤더 컬러의 시크 스타일 레이온 베스트
라벤더 컬러의 시크 스타일 코튼 베스트
봄 한정 나일론 소재 올리브 블라우스
빈티지 무드의 레드 티셔츠
스포티 무드의 라벤더 오버롤
여름 한정 데님 소재 라벤더 오버롤
여름에 어울리는 레드 티셔츠
트렌디한 레트로룩, 세미오버핏 블라우스 in 겨울
필수템! 스포티 무드의 간절기용 오버롤
필수템! 시크 무드의 가을용 베스트

User ID: 5414
-----------------------------------
가을에 어울리는 네이비 슬랙스
간절기 감성 크롭핏 린넨 후드티
간절기 세미오버핏 오렌지 가죽 숏슬리브 베스트
간절기 시즌, 빈티지 무드의 그레이 울 숏 크롭핏 카디건
간절기 한정 메쉬 소재 그레이 카디건
간절기에 어울리는 그레이 카디건
간절기에 어울리는 네이비 후드티
겨울 시즌, 러블리 무드의 네이비 코튼 숏 오버핏 슬랙스
네이비 컬러의 모던 스타일 울 후드티
봄 시즌, 포멀 무드의 네이비 가죽 숏 세미오버핏 블라우스
오버핏 실루엣의 퍼 후드티
크롭핏 실루엣의 데님 슬랙스
트렌디한 빈티지룩, 루즈핏 카디건 in 겨울

User ID: 7424
-----------------------------------
가을 감성 세미오버핏 플리스 레깅스
간절기 슬림핏 민트 아크릴 숏 레깅스
간절기 시즌, 빈티지 무드의 그레이 울 숏 크롭핏 카디건
간절기 한정 메쉬 소재 그레이 카디건
간절기에 어울리는 그레이 카디건
겨울 감성 레귤러핏 모달 레깅스
겨울 한정 레이온 소재 민트 레깅스
겨울 한정 린넨 소재 민트 레깅스
겨울 한정 메쉬 소재 그레이 점퍼
그레이 컬러의 미니멀 스타일 모달 점퍼
미니멀 무드의 그레이 점퍼
봄 시즌, 모던 무드의 스카이블루 데님 롱슬리브 세미오버핏 스커트
봄 오버핏 민트 스웨이드 롱슬리브 레깅스
스카이블루 컬러의 시크 스타일 데님 레깅스
스카이블루 컬러의 시크 스타일 린넨 레깅스
시크 무드의 스카이블루 레깅스
여름 한정 메쉬 소재 그레이 점퍼
여름에 어울리는 스카이블루 스커트
트렌디한 모던룩, 루즈핏 스커트 in 여름
트렌디한 빈티지룩, 루즈핏 카디건 in 겨울
트렌디한 시크룩, 레귤러핏 레깅스 in 봄

## Item Similarity

In [7]:
# 상품 벡터 ANN 인덱스 생성
item_index = build_index(item_vectors)

# 질의할 상품 선택
item_idx = 0
query_vector = item_vectors[item_idx]  # 해당 상품의 임베딩 벡터

# ANN 검색 실행 (`query_vector`와 가장 가까운 Top-5 상품 탐색)
result = search(query_vector, item_index, top_k=5)
print(result)  # 예: {1: 0.9, 2: 0.8, ...}

{0: 1.0000001192092896, 4257: 0.9915370941162109, 5660: 0.9843361377716064, 129: 0.47835004329681396, 6676: 0.4782578945159912}

In [8]:
# 상품 유사성을 확인하기 위한 메타 데이터 로드
item_metadata_path = Path(base_dir).joinpath(
    f"data/dataset/{DOMAIN}/item_metadata.parquet"
)
df_item = pd.read_parquet(item_metadata_path)

In [9]:
# 질의 상품 제목 조회
item_id = item_id_maps[item_idx]

print(f"Item ID: {item_id}")
print(df_item[df_item["item_id"] == item_id]["title"].item())

Item ID: 1
겨울 감성 세미오버핏 나일론 셔츠

In [10]:
# 유사 상품 제목 조회
similar_indies = list(result.keys())[1:]  # 첫 번째는 자기 자신과의 유사도이므로 제외
similar_item_ids = [item_id_maps[i] for i in similar_indies]

for item_id in similar_item_ids:
    print(f"\nItem ID: {item_id}")
    print("-----------------------------------")
    for t in sorted(df_item[df_item["item_id"] == item_id]["title"]):
        print(t)

Item ID: 4259
-----------------------------------
네이비 컬러의 모던 스타일 울 셔츠

Item ID: 5663
-----------------------------------
세미오버핏 실루엣의 플리스 셔츠

Item ID: 130
-----------------------------------
가을에 어울리는 핑크 베스트

Item ID: 6680
-----------------------------------
스카이블루 컬러의 빈티지 스타일 코튼 조끼

# Recommendation
- User to Item 상품 추천

In [11]:
# 질의 유저 선택
user_idx = 0
query_vector = user_vectors[user_idx]

# 상품 벡터 인덱스에 질의한 결과 획득
result = search(query_vector, item_index, top_k=10)

# 추천 상품 ID (원본 ID가 아닌 별도의 인덱스)
item_indies = list(result.keys())

# 추천 상품 ID 재매핑
recommendation = {}
for i in item_indies:
    # 원본 ID로 매핑
    item_id = item_id_maps[i]
    recommendation[item_id] = result[i]

recommendation

{579: 0.700145959854126,
 7125: 0.6793231964111328,
 129: 0.6682227253913879,
 2194: 0.6428489089012146,
 4877: 0.6407299637794495,
 5194: 0.6378349661827087,
 4723: 0.6337680220603943,
 1407: 0.6185694932937622,
 8484: 0.6100409030914307,
 6021: 0.5913515686988831}

In [12]:
# 추천 상품 상세 보기
df_recommendation = df_item[
    df_item["item_id"].isin(list(recommendation.keys()))
].reset_index(drop=True)

# 추천 상품 점수(유사도) 추가
df_recommendation["score"] = df_recommendation["item_id"].map(recommendation)

# 점수별 내림차순 정렬
df_recommendation = df_recommendation.sort_values(
    "score", ascending=False, ignore_index=True
)

In [13]:
# 해당 유저의 히스토리 조회
df[df["user_id"] == user_id_maps[user_idx]].reset_index(drop=True)

,user_id,item_id,timestamp,action,age,gender,title,color,style,fit,material,season,sleeve,category
0,1,2194,2025-09-21 03:01:00,click,46,F,블랙 컬러의 스포티 스타일 레이온 청바지,블랙,스포티,레귤러핏,레이온,봄,롱,청바지
1,1,4723,2025-09-21 03:02:00,click,46,F,크롭핏 실루엣의 메쉬 청바지,블랙,스포티,크롭핏,메쉬,가을,롱,청바지
2,1,2689,2025-09-02 00:05:00,click,46,F,빈티지 무드의 레드 티셔츠,레드,빈티지,슬림핏,플리스,여름,롱,티셔츠
3,1,7981,2025-09-02 00:09:00,click,46,F,"겨울 시즌, 빈티지 무드의 레드 플리스 숏슬리브 크롭핏 티셔츠",레드,빈티지,크롭핏,플리스,겨울,숏슬리브,티셔츠
4,1,1770,2025-09-02 00:11:00,wishlist,46,F,필수템! 빈티지 무드의 간절기용 티셔츠,레드,빈티지,오버핏,린넨,간절기,롱슬리브,티셔츠
5,1,4443,2025-09-02 00:08:00,click,46,F,간절기 슬림핏 레드 모달 민소매 티셔츠,레드,빈티지,슬림핏,모달,간절기,민소매,티셔츠
6,1,2067,2025-09-06 22:27:00,click,46,F,"트렌디한 시크룩, 오버핏 니트 in 봄",베이지,시크,오버핏,린넨,봄,롱슬리브,니트
7,1,1980,2025-09-06 22:31:00,click,46,F,베이지 컬러의 시크 스타일 울 니트,베이지,시크,슬림핏,울,간절기,롱슬리브,니트
8,1,9647,2025-09-06 22:33:00,click,46,F,시크 무드의 베이지 니트,베이지,시크,레귤러핏,퍼,봄,숏,니트
9,1,1407,2025-09-26 01:46:00,click,46,F,"가을 시즌, 댄디 무드의 올리브 폴리 롱 슬림핏 스커트",올리브,댄디,슬림핏,폴리,가을,롱,스커트
10,1,5194,2025-09-26 01:47:00,click,46,F,"트렌디한 댄디룩, 슬림핏 스커트 in 가을",올리브,댄디,슬림핏,퍼,가을,7부,스커트
11,1,8484,2025-09-26 01:50:00,click,46,F,간절기 오버핏 올리브 린넨 숏 스커트,올리브,댄디,오버핏,린넨,간절기,숏,스커트
12,1,6021,2025-09-26 01:49:00,wishlist,46,F,슬림핏 실루엣의 린넨 스커트,올리브,댄디,슬림핏,린넨,봄,숏슬리브,스커트
13,1,7125,2025-09-28 03:24:00,click,46,F,"트렌디한 빈티지룩, 루즈핏 카디건 in 겨울",그레이,빈티지,루즈핏,코튼,겨울,숏슬리브,카디건
14,1,4877,2025-09-28 03:27:00,click,46,F,"간절기 시즌, 빈티지 무드의 그레이 울 숏 크롭핏 카디건",그레이,빈티지,크롭핏,울,간절기,숏,카디건
15,1,579,2025-09-28 03:26:00,click,46,F,간절기에 어울리는 그레이 카디건,그레이,빈티지,루즈핏,스웨이드,간절기,7부,카디건
16,1,129,2025-09-28 03:30:00,click,46,F,간절기 한정 메쉬 소재 그레이 카디건,그레이,빈티지,세미오버핏,메쉬,간절기,롱슬리브,카디건

In [14]:
# 추천 상품 최종 후보군 조회
df_recommendation

,item_id,title,color,style,fit,material,season,sleeve,category,score
0,579,간절기에 어울리는 그레이 카디건,그레이,빈티지,루즈핏,스웨이드,간절기,7부,카디건,0.700146
1,7125,"트렌디한 빈티지룩, 루즈핏 카디건 in 겨울",그레이,빈티지,루즈핏,코튼,겨울,숏슬리브,카디건,0.679323
2,129,간절기 한정 메쉬 소재 그레이 카디건,그레이,빈티지,세미오버핏,메쉬,간절기,롱슬리브,카디건,0.668223
3,2194,블랙 컬러의 스포티 스타일 레이온 청바지,블랙,스포티,레귤러핏,레이온,봄,롱,청바지,0.642849
4,4877,"간절기 시즌, 빈티지 무드의 그레이 울 숏 크롭핏 카디건",그레이,빈티지,크롭핏,울,간절기,숏,카디건,0.640730
5,5194,"트렌디한 댄디룩, 슬림핏 스커트 in 가을",올리브,댄디,슬림핏,퍼,가을,7부,스커트,0.637835
6,4723,크롭핏 실루엣의 메쉬 청바지,블랙,스포티,크롭핏,메쉬,가을,롱,청바지,0.633768
7,1407,"가을 시즌, 댄디 무드의 올리브 폴리 롱 슬림핏 스커트",올리브,댄디,슬림핏,폴리,가을,롱,스커트,0.618569
8,8484,간절기 오버핏 올리브 린넨 숏 스커트,올리브,댄디,오버핏,린넨,간절기,숏,스커트,0.610041
9,6021,슬림핏 실루엣의 린넨 스커트,올리브,댄디,슬림핏,린넨,봄,숏슬리브,스커트,0.591352